### ISSUE TITLE
Evaluation methods for assessing the quality of image-based saliency maps  (XRAI)

### ISSUE THREAD

**Issue by dsvrsec** [PAIR-code/saliency#45] opened 2020-10-22 16:14 UTC
Hi,

Is the code available for Evaluation methods for assessing the quality of image-based saliency maps in XRAI

**Comment by bwedin** [comment] 2021-07-28 17:30
Duplicate of https://github.com/PAIR-code/saliency/issues/39

**Closed by bwedin** 2021-07-28 17:30 UTC
